# This is a basic workflow to help you get started with Actions

name: Quiz app offline 

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
